title: Project
tabs:
  infos:
    label: Infos
    icon: text
    columns:
      - width: 3/4
        sections:
          infos:
            type: fields
            fields:
              subtitle:
                label: Subtitle
                type: text
                width: 3/4
              date:
                label: Year
                type: number
                min: 1900
                width: 1/4
              text:
                label: Description
                type: markdown
                size: medium
                buttons:
                  - link
                  - email
      - width: 1/4
        sections:
          thumbnail:
            type: fields
            fields:
              autoid:
                type: hidden
                translate: false
              featured:
                label: Featured image
                type: files
                multiple: false
                template: image
                uploads: image
              category:
                label: Category
                type: radio
                options: query
                query: page.parent.categories.toStructure
  content:
    label: Content
    sections:
      content:
        type: fields
        fields:
          sections:
            label: Page Content
            type: builder
            columns: 1
            fieldsets:
              image:
                label: Image
                snippet: blocks/image
                fields:
                  file:
                    type: files
                    multiple: false
                    template: image
                    uploads: image
                    layout: cards
              images:
                label: Images
                snippet: blocks/images
                fields:
                  files:
                    type: files
                    multiple: true
                    layout: cards
                    size: tiny
                    template: image
                    uploads: image
              # vimeo:
              #   label: Vimeo
              #   snippet: blocks/vimeo
              #   fields:
              #     page:
              #       type: pages
              #       multiple: false
              #       layout: cards
              #       query: site.find('vimeo').children
              #       image:
              #         cover: false
              #         ratio: 3/2
              #         back: black
              #         query: page.cover.toFile
              #     muted:
              #       label: Muted
              #       type: toggle
              #       default: true
              #       text:
              #         - 'No'
              #         - 'Yes'
              #       width: 1/3
              #     autoplay:
              #       label: Autoplay
              #       type: toggle
              #       default: false
              #       text:
              #         - 'No'
              #         - 'Yes'
              #       width: 1/3
              #     loop:
              #       label: Loop
              #       type: toggle
              #       default: false
              #       text:
              #         - 'No'
              #         - 'Yes'
              #       width: 1/3
              #     controls:
              #       label: Controls
              #       type: toggle
              #       default: false
              #       text:
              #         - 'No'
              #         - 'Yes'
              #       width: 1/3
  files:
    icon: file
    sections:
      files:
        type: files
        layout: list
        template: file
      images:
        type: files
        layout: cards
        template: image
        size: tiny
