title: Project
tabs:
  infos:
    label: Infos
    icon: text
    columns:
      - width: 3/4
        sections:
          infos:
            type: fields
            fields:
              caption:
                label: Caption
                type: text
                width: 3/4
              date:
                label: Year
                type: date
                width: 1/4
              text:
                label: Description
                type: markdown
                size: medium
                buttons:
                  - link
                  - email
                  - bold
                  - italic
      - width: 1/4
        sections:
          thumbnail:
            type: fields
            fields:
              featured:
                label: Featured image
                type: files
                multiple: false
                template: image
  content:
    label: Content
    sections:
      content:
        type: fields
        fields:
          sections:
            label: Page Content
            type: builder
            columns: 1
            fieldsets:
              images:
                label: Images
                snippet: blocks/images
                fields:
                  files:
                    type: files
                    template: image
                    layout: cards
  files:
    icon: file
    sections:
      images:
        type: files
        layout: cards
        template: file
        size: tiny
