title: Site
tabs:
  pages:
    sections:
      pages:
        headline: Pages
        type: pages
        create:
          - default
          - about
          - contact
  settings:
    label: Settings
    icon: cog
    sections:
      infos:
        type: fields
        fields:
          shortTitle:
            label: Short title
            type: text
          tagline:
            label: Tagline
            type: text
          menuPage1:
            label: Menu Page 1
            type: pages
            multiple: false
            width: 1/2
          menuPage2:
            label: Menu Page 2
            type: pages
            multiple: false
            width: 1/2
          description:
            label: Description
            type:  textarea
          keywords:
            label: Keywords
            type:  tags
            width: 1/2
          customcss:
            label: Custom CSS
            type: textarea
            buttons: false
          googleAnalytics:
            label: Google Analytics ID
            type: text
            icon: code
            help: Tracking ID in the form UA-XXXXXXXX-X. Keep this field empty if you are not using it.
            width: 1/2
          ogimage:
            label: Facebook OpenGraph image
            type: files
            multiple: false
            layout: cards
            help: 1200x630px minimum
            width: 1/2
  files:
    icon: file
    sections:
      images:
        type: files
        layout: cards
        template: image
